<?php

// $Id$

function about_menu() {
	$items['about'] = array(
		'title' => t('About Us'),
		'description' => 'about',
		'page callback' => 'about',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['about_action'] = array(
		'title' => t('About Us'),
		'description' => 'about',
		'page callback' => 'about_action',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
        
	return $items;
}

/**
 * Implements hook_theme().
 */
function about_theme($existing, $type, $theme, $path) {
	return array(
		'about' => array(
			'variables' => array('content' => NULL),
			'template' => 'about',
			'path' => drupal_get_path('module', 'about')
		)
	);
}

/**
 * Implements hook_mail()
 * @param 
 *   type $key to decide which email body to sent on basis of key parameter inacese of multiple email content
 * @param 
 *   type $message the email content to be sent.Message array contains 'subject and body ' for the email.
 * @param 
 *   type $params using to get the cusotm email content from a function.This can be used in my other ways aslo as per need.
 */
function about_mail($key, &$message, $params) {
	$language = $message['language'];
  switch ($key) {
    case 'about_email':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
			$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      break;
  }
}

function about() {
	global $base_url;
	
	$jobs = db_query("SELECT nid FROM node WHERE type = 'conext_job'");
	foreach($jobs as $job) {
		$job_detail[] = node_load($job->nid);
	}
	
	$content = array(
		'action' => $base_url. "/about_action",
		'jobs' => $job_detail
	);
	
	//drupal_set_message('<pre>'.print_r($content, true).'</pre>');
	return theme('about', array('content' => $content));
}

function about_action(){
	global $base_url;
	
	if ($_POST) {
		$email_content = "Name: ".$_POST['contact_name']."<br />Email Address: ".$_POST['email_address']."<br />Phone: ".$_POST['phone']."Comapany: ".$_POST['company']."<br /> Message:<br />".$_POST['message'];
		$params = array('body' => $email_content, 'subject' => 'Conext Contact Email');
		$key = 'about_email';
		$to = variable_get('conext_contact_email_to');
		$from = variable_get('conext_email_from');
		$mail = drupal_mail('about', $key, $to, language_default(), $params, $from);
		drupal_set_message('You have submitted the form successfully');
		drupal_goto($base_url.'/about');
	} else {
		drupal_set_message('Invalid Page', 'error');
		drupal_goto($base_url.'/about');
	}
}
