<?php

// $Id$

function job_opening_menu() {
	$items['job_opening/%'] = array(
		'title' => t('Job Opening'),
		'description' => 'Job Opening',
		'page callback' => 'job_opening',
		'page arguments' => array(1),
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_opening_apply'] = array(
		'title' => t('Job Opening Apply'),
		'description' => 'Job Opening Apply',
		'page callback' => 'job_opening_apply',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
        
	return $items;
}

/**
 * Implements hook_theme().
 */
function job_opening_theme($existing, $type, $theme, $path) {
	return array(
		'job_opening' => array(
			'variables' => array('content' => NULL),
			'template' => 'job_opening',
			'path' => drupal_get_path('module', 'job_opening')
		)
	);
}

function job_opening($nid) {
	global $base_url;
	
	$jobs = db_query("SELECT nid, title FROM node WHERE type = 'conext_job'");
	foreach($jobs as $job) {
		$job_openings[] = array('nid' => $job->nid, 'title' => $job->title);
	}
	$job_detail = node_load($nid);

	$content = array(
		'nid' => $nid,
		'job_detail' => $job_detail,
		'job_openings' => $job_openings
	);
	
	//drupal_set_message('<pre>'.print_r($content, true).'</pre>');
	return theme('job_opening', array('content' => $content));
}

function job_opening_apply(){
	global $user, $base_url;
	
	$timestamp = time();
	$path = $_FILES['cv_file']['tmp_name'];
	$file_temp = file_get_contents($path);
	$file_temp = file_save_data($file_temp, 'public://conext_cv/' . $timestamp .'-'. $_FILES['cv_file']['name'], FILE_EXISTS_RENAME);
	//drupal_set_message('<pre>'.print_r($file_temp, true).'</pre>', 'notice');
	
	if (isset($file_temp)) {
		// create conext job applied node
		$node = new stdClass();
		$node->type = 'conext_job_applied';
		$node->status = 1;
		$node->uid = $user->uid;
		$node->title = $_POST['contact_name'];
		$node->promote = 1;
		$node->language = LANGUAGE_NONE;
		$node->created = $timestamp;
		$node->timestamp = $timestamp;
		$node->body[LANGUAGE_NONE][0]['value'] = $_POST['cover_letter'];
		$node->field_job_applied_email[LANGUAGE_NONE][0]['value'] = $_POST['email_address'];
		$node->field_job_applied[LANGUAGE_NONE][0]['value'] = $_POST['job_applied'];
		$node->field_job_applied_cv[LANGUAGE_NONE][0]['value'] = $file_temp->uri;
		node_save($node);
	}
	
	$redirect_url = $base_url.'/'.drupal_get_path_alias("node/".$_POST['nid']);
	drupal_set_message('Your message has been sent successfully', 'notice');
	drupal_goto($redirect_url);
}

function job_opening_node_view($node, $view_mode, $langcode) {
	global $base_url;
  switch ($node->type) {
    case 'conext_job':
			$jobs = db_query("SELECT nid, title FROM node WHERE type = 'conext_job'");
			foreach($jobs as $job) {
				$job_openings[] = array('nid' => $job->nid, 'title' => $job->title);
			}
			$node->content['job_openings'] = $job_openings;
			$node->content['action'] = $base_url."/job_opening_apply";
     
      break;
  }
}