<?php

function job_seeker_menu() {
	$items['job_seeker'] = array(
		'title' => t('Job Seeker'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/account'] = array(
		'title' => t('Job Seeker Account'),
		'description' => 'job_seeker_',
		'page callback' => 'job_seeker_account',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/account/submit'] = array(
		'title' => t('Job Seeker Account'),
		'description' => 'job_seeker_',
		'page callback' => 'job_seeker_account_submit',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/login'] = array(
		'title' => t('Job Seeker Login'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker_login',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/login/submit'] = array(
		'title' => t('Job Seeker Login'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker_login_submit',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/register'] = array(
		'title' => t('Job Seeker Register'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker_register',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/register/submit'] = array(
		'title' => t('Job Seeker Register'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker_register_submit',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
	
	$items['job_seeker/register_complete'] = array(
		'title' => t('Job Seeker Register Complete'),
		'description' => 'job_seeker',
		'page callback' => 'job_seeker_register_complete',
		'access arguments' => true,
		'access callback' => true,
		'type' =>  MENU_CALLBACK,
	);
        
	return $items;
}

/**
 * Implements hook_theme().
 */
function job_seeker_theme($existing, $type, $theme, $path) {
	return array(
		'job_seeker_login' => array(
			'variables' => array('content' => NULL),
			'template' => 'job_seeker_login',
			'path' => drupal_get_path('module', 'job_seeker')
		),
		'job_seeker_register' => array(
			'variables' => array('content' => NULL),
			'template' => 'job_seeker_register',
			'path' => drupal_get_path('module', 'job_seeker')
		),
		'job_seeker_register_thanks' => array(
			'variables' => array('content' => NULL),
			'template' => 'job_seeker_register_thanks',
			'path' => drupal_get_path('module', 'job_seeker')
		),
		'job_seeker_account' => array(
			'variables' => array('content' => NULL),
			'template' => 'job_seeker_account',
			'path' => drupal_get_path('module', 'job_seeker')
		),
	);
}

function job_seeker () {
	global $user, $base_url;
	
	$roles = $user->roles;
	if ( valid_user_role(JOB_SEEKER_ROLE_ID) ) {
		drupal_goto($base_url.'/job_seeker/account');
	} else {
		drupal_goto($base_url.'/job_seeker/login');
	}
}

function job_seeker_account() {
	global $user, $base_url;
	$jobs = array();
	
	if (valid_user_role(JOB_SEEKER_ROLE_ID)) {
		$industries = get_term_list ('company_industry');
		$cities = db_query("SELECT id, nama_kota FROM conext_kota");
		$education_cities = db_query("SELECT id, nama_kota FROM conext_kota");
		$months = conext_get_month();
		$years = conext_get_year();
		$salary_range = get_salary_range_v2();
		$account = db_query("SELECT * FROM users a INNER JOIN conext_job_seeker b ON a.uid = b.user_id WHERE user_id = :user_id", array('user_id' => $user->uid));

		$query_job_applieds = "SELECT title, location, drupal_job_id, b.created_at FROM conext_job a 
				INNER JOIN conext_job_applied b ON a.drupal_job_id = b.job_id 
				INNER JOIN conext_job_seeker c ON c.user_id = b.job_seeker_id
				WHERE b.job_seeker_id = :job_seeker_id";
		$job_applieds = db_query($query_job_applieds, array('job_seeker_id' => $user->uid));
		foreach($job_applieds as $job_applied) {
			$jobs[] = array(
				'title' => $job_applied->title,
				'location' => $job_applied->location,
				'drupal_job_id' => $job_applied->drupal_job_id,
				'created_at' => $job_applied->created_at
			);
		}

		$content = array(
			'industries' => $industries,
			'cities' => $cities,
			'education_cities' => $education_cities,
			'user' => $user,
			'months' => $months,
			'years' => $years,
			'jobs' => $jobs,
			'account' => $account,
			'expected_salary' => $salary_range
		);

		return theme('job_seeker_account', array('content' => $content));
	} else {
		drupal_goto($base_url.'/job_seeker');
	}
}

function job_seeker_account_submit() {
	global $user, $base_url;
	$timestamp = time();
	
	if ($_POST) {
		if (empty($_FILES['cv_file']['tmp_name'])) {
			$cv_path = '';
		} else {
			$path = $_FILES['cv_file']['tmp_name'];
			$file_temp = file_get_contents($path);
			$file_temp = file_save_data($file_temp, 'public://cv/' . $timestamp .'-'. $_FILES['cv_file']['name'], FILE_EXISTS_RENAME);
			$cv_path = $file_temp->uri;
		}
		conext_update_user ($_POST, 'job_seeker', $cv_path);
		drupal_goto($base_url.'/job_seeker/account');
	}
}

function job_seeker_login () {
	global $user, $base_url;
	
	if (valid_user_role(JOB_SEEKER_ROLE_ID)) drupal_goto($base_url.'/jobs');
	
	return theme('job_seeker_login');
}

function job_seeker_login_submit() {
	if ($_POST) {
		conext_login_user ($_POST['username'], $_POST['password'], 'jobs', 'job_seeker/login', JOB_SEEKER_ROLE_ID);
	} else {
		return theme('employer_login');
	}	
}


function job_seeker_register() {
	global $user, $base_url;
	if (!empty($_SESSION['linkedin']['response'])) {
		$first_name = $_SESSION['linkedin']['response']['person']['first-name'];
		$last_name = $_SESSION['linkedin']['response']['person']['last-name'];
		$public_profile_url = $_SESSION['linkedin']['response']['person']['public-profile-url'];
		$email_address = $_SESSION['linkedin']['response']['person']['email-address'];
		$about_yourself = $_SESSION['linkedin']['response']['person']['summary'];
		if (!empty($_SESSION['linkedin']['response']['person']['positions']['position'])) {
			$position = $_SESSION['linkedin']['response']['person']['positions']['position'];
			$current_title = $position['title'];
			$current_start_month = $position['start-date']['month'];
			$current_start_year = $position['start-date']['year'];
			if ($position['is-current'] == 'true') {
				$current_end_month = date('m');
				$current_end_year = date('Y');
				$current_present = 1;
			} else {
				$current_end_month = $position['end-date']['month'];
				$current_end_year = $position['end-date']['year'];
				$current_present = 0;
			}
			$company = $position['company']['name'];
			if (!empty($_SESSION['linkedin']['response']['person']['location'])) {
				$location = $_SESSION['linkedin']['response']['person']['location'];
				$js_location = explode(',', $location['name']);
				$location_length = count($js_location);
				$city = $js_location[0];
				if ($location_length == 3) $province = $js_location[1];
				$country = end($js_location);
			}
		}
	}
	
	$industries = get_term_list ('company_industry');
	$cities = db_query("SELECT id, nama_kota FROM conext_kota");
	$education_cities = db_query("SELECT id, nama_kota FROM conext_kota");
	$months = conext_get_month();
	$years = conext_get_year();
	$salary_range = get_salary_range_v2();
	
	$content = array(
		'industries' => $industries,
		'cities' => $cities,
		'education_cities' => $education_cities,
		'user' => $user,
		'months' => $months,
		'years' => $years,
		'first_name' => (empty($first_name)) ? '' : $first_name,
		'last_name' => (empty($last_name)) ? '' : $last_name,
		'public_profile_url' => (empty($public_profile_url)) ? '' : $public_profile_url,
		'email_address' => (empty($email_address)) ? '' : $email_address,
		'about_yourself' => (empty($about_yourself)) ? '' : $about_yourself,
		'current_title' => (empty($current_title)) ? '' : $current_title,
		'current_start_month' => (empty($current_start_month)) ? '' : $current_start_month,
		'current_start_year' => (empty($current_start_year)) ? '' : $current_start_year,
		'current_end_month' => (empty($current_end_month)) ? '' : $current_end_month,
		'current_end_year' => (empty($current_end_year)) ? '' : $current_end_year,
		'current_present' => (empty($current_present)) ? '' : $current_present,
		'company' => (empty($company)) ? '' : $company,
		'city' => (empty($city)) ? '' : $city,
		'country' => (empty($country)) ? '' : $country,
		'province' => (empty($province)) ? '' : $province,
		'expected_salary' => $salary_range
	);
	//drupal_set_message("<pre>".print_r($_SESSION['linkedin'], true)."</pre>");
	
	return theme('job_seeker_register', array('content' => $content));
}


function job_seeker_register_submit() {
	if ($_POST) {
		$timestamp = time();
		
		if (empty($_FILES['cv_file']['tmp_name'])) {
			$cv_path = '';
		} else {
			$path = $_FILES['cv_file']['tmp_name'];
			$file_temp = file_get_contents($path);
			$file_temp = file_save_data($file_temp, 'public://cv/' . $timestamp .'-'. $_FILES['cv_file']['name'], FILE_EXISTS_RENAME);
			$cv_path = $file_temp->uri;
		}
		
		$uid = conext_register_user($_POST, 'job_seeker', $cv_path);
		
		// login user
		$account = user_load($uid);
		$form_state = array();
		$form_state['uid'] = $account->uid;      
		user_login_submit(array(), $form_state);

		drupal_goto('job_seeker/register_complete');

	}
}

function job_seeker_register_complete() {
	return theme('job_seeker_register_thanks');
}