<?php
// $Id$

function custom_form_alter_form_alter(&$form, &$form_state, $form_id) {
	//print "<pre>".print_r($form, true)."</pre>";
	//print $form_id;
	global $user;
	//print $form_id;
	//print '<br />';
	//print $user->uid;
	
	if($form_id == "views_form_admin_views_user_system_1" && $user->uid != 1) {
    $keys = array('name', 'status', 'roles', 'member_for', 'last_access', 'operations');
    foreach($keys as $key) {
      unset($form[$key][1]);
    }
    unset($form['accounts']['#options'][1]);
  }
	
	if($form_id == 'article_node_form') {
		$form['actions']['submit']['#submit'][] = 'article_node_form_submit_handler';
	}
	else if($form_id == 'conext_job_applied_node_form') {
		$form['actions']['submit']['#submit'][] = 'conext_job_applied_node_form_submit_handler';
	}
	else if($form_id == 'article_category_node_form') {
		$form['actions']['submit']['#submit'][] = 'article_category_node_form_submit_handler';
	}
	else if($form_id == 'client_node_form') {
		$form['actions']['submit']['#submit'][] = 'client_node_form_submit_handler';
	}
	else if($form_id == 'conext_job_node_form') {
		$form['actions']['submit']['#submit'][] = 'conext_job_node_form_submit_handler';
	}
	else if($form_id == 'testimonial_node_form') {
		$form['actions']['submit']['#submit'][] = 'testimonial_node_form_submit_handler';
	}
	else if($form_id == 'intro_node_form') {
		$form['actions']['submit']['#submit'][] = 'intro_node_form_submit_handler';
	}
	else if($form_id == 'banner_node_form') {
		$form['actions']['submit']['#submit'][] = 'banner_node_form_submit_handler';
	}
}

function article_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/article';   
}

function conext_job_applied_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/applied-job-opening';   
}

function article_category_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/article-category';   
}

function client_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/client';   
}

function conext_job_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/job-opening';   
}

function testimonial_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/testimonial';   
}

function intro_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/intro';   
}

function banner_node_form_submit_handler($form, &$form_state) {
    $form_state['redirect']  = 'admin/banner';   
}
?>